export const MESSAGES = {
  START_TIMER: 'START_TIMER',
  PAUSE_TIMER: 'PAUSE_TIMER',
  RESET_TIMER: 'RESET_TIMER',
  GET_STATUS: 'GET_STATUS',
  STOP_TIMER: 'STOP_TIMER',
  GET_TIMER_STATE: 'GET_TIMER_STATE',
  TIMER_UPDATE: 'TIMER_UPDATE',
  REQUEST_TEMP_ACCESS: 'REQUEST_TEMP_ACCESS'
};

export interface MessagePayload {
  type: keyof typeof MESSAGES;
  payload?: any;
}
